### ISSUE TITLE
wrongly date vax data?

### ISSUE THREAD

**Issue by lomotech** [akutaktau/covid-19-data#63]
macam hari ni, 21/6 tapi gambar daripada mkn mengatakan 20/6 kan?

**Comment by akutaktau** [comment]
date kita ikut date gambar dikeluarkan

**Comment by lomotech** [comment]
contoh 

```
{
    "date": "2021-06-22",
    "perlis": {
      "registered": 115835,
      "dose_1": 57691,
      "dose_2": 29496
    },
}
```

daripada mkn 22 jun 2021 11:59 malam (dishare di mkn channel 23 jun)

perlis 59520, 31403
so data mkn ni masuk 22 atau 23?

**Comment by akutaktau** [comment]
23

**Comment by lomotech** [comment]
okeh
